name: ci

on:
  push:
    paths:
      - 'src/**'
    # - '.github/workflows/ci.yaml'
    branches:
      - main
env:  
  COMMIT_ID=$(git rev-parse --short "$GITHUB_SHA")
  
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      

      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: leoherso/python-app:${{ env.COMMIT_ID }}
         